apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  namespace: {{ .Values.namespace | default "model-serving" }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 30000
      protocol: TCP
      targetPort: 8080
  type: ClusterIP